### ISSUE TITLE
Issue with line 289 on child.py and the wsCsv variable

### ISSUE THREAD

**Issue by Nguyentrandz** [awslabs/workspaces-cost-optimizer#1]
I found there are two CostOptimizerChildFunction functions.

Lambda didn't work since last modification or even after the Lambda was created. 
Also the error shows it is an Syntax error in child.py, line 289. 

Can you please review your code in child.py code/code snippet around line 289 for any error?

**Comment by thomasphorton** [comment]
Better late than never- we've got a fix for this coming. `wsBillable` is being returned as an `int` and not a `str` in some cases.

This repository is getting an overhaul soon, once we run through an internal code-review process. It'll be more modular and have proper unit tests. Apologies for letting this languish- should have something out by the end of next week.

**Comment by Nguyentrandz** [comment]
Nice. Thanks for looking into this.

**Comment by thomasphorton** [comment]
Would you be interested in running an early release of the new version? We're looking good in our test environments but would love some customer data.

**Comment by thomasphorton** [comment]
Good news! We've updated the solution. The GitHub repo lags a little behind our prod assets, but in the mean time you can see the solution here: https://aws.amazon.com/answers/account-management/workspaces-cost-optimizer/

Thank you for helping diagnose!

**Comment by stevemorad** [comment]
New version of code was just pushed. Resovling this issue.
