### ISSUE TITLE
Why is InsessionLatency used for assessment of Monthly activity?

### ISSUE THREAD

**Issue by manbearpigisreal** [awslabs/workspaces-cost-optimizer#10]
What is the logic behind using InSessionLatency as the defining metric for Monthly workspace activity? What does that metric actually measure?

**Comment by manbearpigisreal** [comment]
I see that it does RTT to the client, but what if the cilent is using a PCOIP zero client?

**Comment by k4n30** [comment]
https://github.com/awslabs/workspaces-cost-optimizer/commit/4857119e37b3567f950934751271a8a4cb45ae21#diff-3d526d6575aa9ba2e51771a119f16f5aR87

Comment might explain it

**Comment by k4n30** [comment]
To expand on this, I've just realised that the InSessionLatency metric is only recorded when the user uses the Workspaces client (https://docs.aws.amazon.com/workspaces/latest/adminguide/cloudwatch-metrics.html), so it's not just those who use the PCOIP zero client, it's also those who use the web access - https://clients.amazonworkspaces.com/webclient

**Comment by deolank** [comment]
We have updated the metric to "UserConnected" for calculation of billable hours. Please deploy the latest version of our solution to get the changes.
