### ISSUE TITLE
Unable to assume the service linked role

### ISSUE THREAD

**Issue by suliman317** [awslabs/workspaces-cost-optimizer#13]
Hello, I was able to deploy the cloud formation template. however, I am getting the following issue when running the lambda functions. 

[ERROR] InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
Traceback (most recent call last):
  File "/var/task/source/helpers/create-task.py", line 54, in lambda_handler
    'assignPublicIp': 'ENABLED'
  File "/var/runtime/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by suliman317** [comment]
[ERROR] InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
Traceback (most recent call last):
  File "/var/task/source/helpers/create-task.py", line 54, in lambda_handler
    'assignPublicIp': 'ENABLED'
  File "/var/runtime/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 623, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by suliman317** [comment]
Here are the roles of the cloud formation template created. I don't think its creating service roles

`{
            "Path": "/",
            "RoleName": "WorkSpacesCostOptimizer-CostOptimizerAdminRole-1PN6BJEPH8JN9",
            "RoleId": "AROASNHPEEPL4HIGIR4JC",
            "Arn": "arn:aws:iam::165857731543:role/WorkSpacesCostOptimizer-CostOptimizerAdminRole-1PN6BJEPH8JN9",
            "CreateDate": "2019-09-06T21:35:59Z",
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": {
                            "Service": "ecs-tasks.amazonaws.com"
                        },
                        "Action": "sts:AssumeRole"
                    }
                ]
            },
            "Description": "",
            "MaxSessionDuration": 3600
        },
        {
            "Path": "/",
            "RoleName": "WorkSpacesCostOptimizer-CostOptimizerLambdaRole-1AFTFDXYIX3HK",
            "RoleId": "AROASNHPEEPLZJRROV7DN",
            "Arn": "arn:aws:iam::165857731543:role/WorkSpacesCostOptimizer-CostOptimizerLambdaRole-1AFTFDXYIX3HK",
            "CreateDate": "2019-09-06T21:36:00Z",
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": {
                            "Service": "lambda.amazonaws.com"
                        },
                        "Action": "sts:AssumeRole"
                    }
                ]
            },
            "Description": "",
            "MaxSessionDuration": 3600
        },
        {
            "Path": "/",
            "RoleName": "WorkSpacesCostOptimizer-SolutionHelperRole-7LXNOOMS0UPI",
            "RoleId": "AROASNHPEEPLQHEFSESVJ",
            "Arn": "arn:aws:iam::165857731543:role/WorkSpacesCostOptimizer-SolutionHelperRole-7LXNOOMS0UPI",
            "CreateDate": "2019-09-06T21:35:59Z",
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": {
                            "Service": "lambda.amazonaws.com"
                        },
                        "Action": "sts:AssumeRole"
                    }
                ]
            },
            "Description": "",
            "MaxSessionDuration": 3600
        },`

**Comment by JekzVadaria** [comment]
Execute this command in your AWS CLI aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com 
It will create the needed service linked role for the ECS in your AWS Account and your Lambda will not throw [ERROR] InvalidParameterException.
