### ISSUE TITLE
Scanning Workspace Directories fail, when there is explict deny on resources in some regions.

### ISSUE THREAD

**Issue by FilipByrski** [awslabs/workspaces-cost-optimizer#14]
If there is explicit deny on some regions, python script fail to get list of workspaces.

`ERROR: An error occurred (AccessDeniedException) when calling the DescribeWorkspaceDirectories operation: User: arn:aws:sts::xxxxxxxxxx:assumed-role/workspaces-cost-optimizer-CostOptimizerAdminRole-xxxxxxxxxxx/xxxxxxxxxxxx is not authorized to perform: workspaces:DescribeWorkspaceDirectories on resource: arn:aws:workspaces:ap-northeast-1:xxxxxxxxxxxx:directory/* with an explicit deny`

**Comment by dscpinheiro** [comment]
Hi @FilipByrski,

Sorry for the delay in the response.
Unfortunately the role requires that permission in order for the solution to work properly.

**Comment by FilipByrski** [comment]
It could just skip disabled regions.
This is not big problem for me, fortunately I have access to organizational account and can unblock this api calls for disabled regions.

**Comment by dscpinheiro** [comment]
You're right, that's definitely a possibility.
I'll add that to the backlog of the solution.
