### ISSUE TITLE
Additional Columns within Report sent.

### ISSUE THREAD

**Issue by keagansc2** [awslabs/workspaces-cost-optimizer#15]
Hi,

I would just like to know what is the best way to add an additional column(s) in the Report being sent to the S3 Bucket. For example I would like to have the "Username" of the Workspace be sent as well in conjunction of the other statistics.

I did investigate into the "workspaces_helper.py" within the "workspaces-cost-optimizer.zip" code and saw some referencing to the csv however, could not find were or if possible these extra parameters could be given and altered.

Any information would help greatly.

**Comment by dscpinheiro** [comment]
Hi @keagansc2,

Here's what you'd have to do to add the Username property (although it should work for any value returned in returned in the [_describe-workspaces_](https://docs.aws.amazon.com/cli/latest/reference/workspaces/describe-workspaces.html#output) API):

- Modify the process_workspace method on workspaces_helper to return the new property:
```python
return {
    'workspaceID': workspaceID,
    'billableTime': billableTime,
    'hourlyThreshold': hourlyThreshold,
    'optimizationResult': optimizationResult['resultCode'],
    'newMode': optimizationResult['newMode'],
    'bundleType': workspaceBundleType,
    'initialMode': workspaceRunningMode,
    'userName': workspace['UserName']
}
```

- Update the append_entry method on workspaces_helper to include the new property:
```python
csv = oldCsv + s.join((
    result['workspaceID'],
    str(result['billableTime']),
    str(result['hourlyThreshold']),
    result['optimizationResult'],
    result['bundleType'],
    result['initialMode'],
    result['newMode'],
    result['userName'] + '\n'
))
```

- Update the CSV header on directory_reader: https://github.com/awslabs/workspaces-cost-optimizer/blob/0162dc18daf51ae4fa8709f5e9a04e36604bf3ec/source/engine/lib/directory_reader.py#L77-L79

Please let us know if that works for you.

**Comment by mstarace** [comment]
Where exactly can I find workspaces_helper?  I am new to this and trying to get Username added to the report as well.

**Comment by dscpinheiro** [comment]
The helper is on this folder: source/engine/lib

https://github.com/awslabs/workspaces-cost-optimizer/blob/4e39def2a98bafa9c2f2b99e844cd5a53e665877/source/engine/lib/workspaces_helper.py

**Comment by carpnick** [comment]
+1 as a feature and default it in the report for reporting use cases (multiple teams)

**Comment by deolank** [comment]
Thanks for your feedback. We have added this as feature to our product backlog and plan to include this in our next release.

**Comment by bgdnlp** [comment]
I'd also like to see this. Any ETA on when the next release might come around, approximately? wondering if it's worth waiting for or I should build the container image myself.

**Comment by rakshb** [comment]
@bgdnlp Hello, we plan to release this capability in Q2 2021

**Comment by rakshb** [comment]
@keagansc2 Hello! this feature was added in V2.3 released today. Thanks!
