### ISSUE TITLE
Is "UserConnected" metric a better choice?

### ISSUE THREAD

**Issue by wzx0z** [awslabs/workspaces-cost-optimizer#16]
Hello,

Similar to issue #10 . I'm trying to use cost optimizer to calculate the hourly WorkSpace usage for each WorkSpace. As AWS WorkSpace FAQs saying, they recommend using "UserConnected" metric for calculation. 

So is "UserConnected" better than "Stopped" and "InsessionLatency" for both AutoStop and AlwaysOn running mode?

Thank you.

**Comment by deolank** [comment]
We have updated the metric to "UserConnected" for calculation of billable hours. Please deploy the latest version of our solution to get the changes.
