### ISSUE TITLE
Failed to update execution schedule for CloudWatch Rule

### ISSUE THREAD

**Issue by matyuda** [awslabs/workspaces-cost-optimizer#18]
Hi,

I tried to update execution schedule for CloudWatch Rule  but failed and raise following error message.
1 validation error detected: Value 'AWSEvents_WorkSpacesCostOptimizer-CostOptimizerScheduleRule-XXXXXXXXXXXX_CostOptimizerCreateTaskFunction' at 'statementId' failed to satisfy constraint: Member must have length less than or equal to 100.

How should I update the execution schedule?

**Comment by deolank** [comment]
This seems to be a bug in the CloudWatch event console. Please follow the steps in the link below for the workaround: https://github.com/concurrencylabs/aws-pricing-tools/issues/8

**Comment by matyuda** [comment]
@deolank 
Thank you for telling me for the workaround.

**Comment by SamKhGit** [comment]
@deolank
Is it a bug in CloudWatch console or the the issue is length of the rule name (106 characters) with the default Stack name?

**Comment by deolank** [comment]
The is an issue due to long (default) stack name. Please use a shorter stack name to get around this issue. We will change the rule name in the next release. You can also try the workaround above if you currently have a stack deployed.
