### ISSUE TITLE
Permissions Error >> Support GovCloud Region 

### ISSUE THREAD

**Issue by olawaley1** [awslabs/workspaces-cost-optimizer#19]
We are getting the following error when running the CFT:

Your access has been denied by S3, please make sure your request credentials have permission to GetObject for solutions-us-gov-west-1/workspaces-cost-optimizer/v2.2.1/workspaces-cost-optimizer.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 51f1da3e-6325-4941-814b-c5982a9f8e52)

Can you confirm if we are supposed to use the WorkSpaces VPC/subnets?

**Comment by rakshb** [comment]
Hello @olawaley1 The solution currently doesn't support Gov Cloud regions. I'm adding this as a backlog item for a future release. Thank you

**Comment by hnishar** [comment]
Release v2.4.0 has the support for the Gov Cloud region
