### ISSUE TITLE
Cloudwatch measurement interval set to 5 minutes lead to wrong calculations

### ISSUE THREAD

**Issue by Sinnohd** [awslabs/workspaces-cost-optimizer#23]
With the latest release, you changed the cloudwatch metrics from one hour to five minutes. However, with intermittent connections (for whatever reason) this leads to multiple sessions per day and on each session it will add one hour for idle time (if workspace is in auto-stop modus). So, something what was with the old version counted for 28 hours, now shows 92 hours!

Five min period for user_connected metric:
![5 min period](https://user-images.githubusercontent.com/2531453/124497958-eecd8000-ddbb-11eb-8844-501721e14302.png)

One hour period for user_connected metric:
![1 hour period](https://user-images.githubusercontent.com/2531453/124497739-9bf3c880-ddbb-11eb-8dfe-cd58cd99d864.png)

This is the data for three days:

Old model + idle_time_in_hours:
```
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
Calculated user connected hours: 31.0
31.0
```
New model:

```
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0]
[1.0, 1.0]
[1.0, 1.0]
[1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[1.0]
Calculated user connected hours: 92.0
92.0
```

As a quick fix for this I changed in my local installation in metrics_helper.py in line 121 the period value from 300 to 3600 and in line 166 change  `math.ceil(len(session) / 12) ` to just ` len(session).`  I kept the adding of idle_time_in_hours, which the old version doesn't had. 

As a feature request for a future release, you could add for auto_stop instances additional four hours for patch time per month.

**Comment by deolank** [comment]
Thanks for your feedback. We have added this to our backlog and will be fixed in our next release.

**Comment by pharindoko** [comment]
Any update on this - can confirm that I get wrong billable hours ...

**Comment by pharindoko** [comment]
hmm the truth lies somewhere in between in my eyes. You have that short time intervals when you disconnect and reconnect that it doesn`t autostop. But my assumption is that this will be counted ...

**Comment by pharindoko** [comment]
ok I guess I figured it out ... following code should deliver a better result
it will append metrics with 0.0 (disconnected) if it happens in a timeframe of 60 minutes as for this timeframe is billable. Only if the disconnected metrics are more than 12 (60 / 5 ) a new session will be created because the instance got autostopped and won`t be billed anymore. 

metricshelper.yml

```python
    def get_list_user_session_data_points(self, list_metric_data_points):
        """
        This method returns the list of data points per user session.
        :param list_metric_data_points:
        :return: list of data points per user session
        """
        log.debug("Getting the list of user session data points for metric data points {}".
                  format(list_metric_data_points))
        list_data_points = []
        list_user_sessions = []
        counter = 0
        sorted_list_metric_data_points = sorted(list_metric_data_points, key=lambda x: x['Timestamp'])
        for metric in sorted_list_metric_data_points:
            if metric["Maximum"] == 1.0:
                list_data_points.append(metric)
                counter = 0
            elif counter > 11:
                list_user_sessions.append(list_data_points)
                list_data_points = [] 
                counter = 0
            elif len(list_data_points) > 0 and metric["Maximum"] == 0.0:
                list_data_points.append(metric)
                counter += 1
```

as it appends at the end of each session as well at least 12 metrics with 0.0 the idle hours are already added (expecting you use autostop with 60 minutes)

Means we don`t need to add the idle hours anymore.
```python
        for session in list_user_sessions:
            # Divide each session by 12 to convert the 5 min intervals to hour and idle time per session
            user_connected_hours = user_connected_hours + math.ceil(len(session) / 12)
        return user_connected_hours
```

**Comment by pharindoko** [comment]
Is anyone maintaining this repository ?

**Comment by deolank** [comment]
This issue will be fixed in the next release of the solution.

**Comment by hnishar** [comment]
The fix for this issue has been pushed out in release v2.4.0
