### ISSUE TITLE
Eliminate more calls to API

### ISSUE THREAD

**Issue by woznij** [awslabs/workspaces-cost-optimizer#5]
Noticed a new property available in the data returned from describe_workspaces:
'WorkspaceProperties': {
        ...
        'ComputeTypeName': 'VALUE'|'STANDARD'|'PERFORMANCE'|'POWER'|'GRAPHICS'
}

If you use this property, you should be able to eliminate calling describe_workspace_bundles.

**Comment by thomasphorton** [comment]
great find! we'll put this in our queue. thanks!

**Comment by deolank** [comment]
We have removed the API call for describe_workspace_bundles. Please deploy the latest version of our solution to get the changes.
