### ISSUE TITLE
Billable hours greater than number of hours in month.

### ISSUE THREAD

**Issue by Belfine** [awslabs/workspaces-cost-optimizer#9]
Hi,

I find it very odd that several Workspaces in my report have billable hours higher than the actual hours passed this month so far. I have several machines listed at 616 hours in today's report (18 of February) which evens out to about 34 hours each day.

ws-example | 616 | 85 | No Change | STANDARD | ALWAYS_ON | ALWAYS_ON

Is there something I am misunderstanding or is this a bug?

Please reach out if you need any additional info.

**Comment by hayesry** [comment]
Hi @Belfine,

Thanks for your post regarding this issue. This is a known issue for the Monthly Billing (Always On) configuration and is being addressed in the next release of the solution. Stay tuned!

Best, 
Ryan
